<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="LAPTOP-UROTC647" name="com.sauce.qa.testcases.ProductDescriptionPageTest" tests="7" failures="0" timestamp="25 Aug 2021 16:12:21 GMT" time="1.412" errors="1">
  <testcase name="setUp" time="1.412" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.sauce.qa.testcases.ProductDescriptionPageTest.setUp(ProductDescriptionPageTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="validateImageDisplayedTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- validateImageDisplayedTest -->
  <testcase name="validateProductTitleTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- validateProductTitleTest -->
  <testcase name="validateAddToCartTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- validateAddToCartTest -->
  <testcase name="removeFromCartTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- removeFromCartTest -->
  <testcase name="validateBackToProductsTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- validateBackToProductsTest -->
  <testcase name="validateYourCartTest" time="0.000" classname="com.sauce.qa.testcases.ProductDescriptionPageTest">
    <skipped/>
  </testcase> <!-- validateYourCartTest -->
</testsuite> <!-- com.sauce.qa.testcases.ProductDescriptionPageTest -->
